#!/bin/bash
source ./ENV

rm -rf $ENV_EXPORT_INCLUDES_DIRPATH && mkdir -p $ENV_EXPORT_INCLUDES_DIRPATH
rm -rf $ENV_EXPORT_ENGINE_DIRPATH && mkdir -p $ENV_EXPORT_ENGINE_DIRPATH
rm -rf $ENV_EXPORT_EDITOR_STANDALONE_DIRPATH && mkdir -p $ENV_EXPORT_EDITOR_STANDALONE_DIRPATH
rm -rf $ENV_EXPORT_EXPORTTOOL_DIRPATH && mkdir -p $ENV_EXPORT_EXPORTTOOL_DIRPATH

# Includes
cp -r ./include/coconuts2D "$ENV_EXPORT_INCLUDES_DIRPATH" 2>/dev/null
cp -r ./include/thirdparty/ "$ENV_EXPORT_INCLUDES_DIRPATH" 2>/dev/null
