#!/bin/bash
source ./ENV

rm -rf $ENV_COCONUTS2D_EXPORT_INCLUDES_DIRPATH && mkdir -p $ENV_COCONUTS2D_EXPORT_INCLUDES_DIRPATH
rm -rf $ENV_COCONUTS2D_EXPORT_ENGINE_DIRPATH && mkdir -p $ENV_COCONUTS2D_EXPORT_ENGINE_DIRPATH
rm -rf $ENV_COCONUTS2D_EXPORT_EDITOR_STANDALONE_DIRPATH && mkdir -p $ENV_COCONUTS2D_EXPORT_EDITOR_STANDALONE_DIRPATH

# Single Engine Library (no Editor)
cd ./build
rm -rf *
cmake -DCOMPILE_GAME_EDITOR=OFF ..
make combined
cp ./src/libccn2d.a "$ENV_COCONUTS2D_EXPORT_ENGINE_DIRPATH/$ENV_COCONUTS2D_EXPORT_ENGINE_OUTNAME" 2>/dev/null

# Game Editor Application
make clean
cmake -DCOMPILE_GAME_EDITOR=ON ..
make
cp ./src/editor/Coconuts2D "$ENV_COCONUTS2D_EXPORT_EDITOR_STANDALONE_DIRPATH/$ENV_COCONUTS2D_EXPORT_EDITOR_STANDALONE_OUTNAME" 2>/dev/null

# Install headers
cd ..
cp -r ./include/coconuts2D "$ENV_COCONUTS2D_EXPORT_INCLUDES_DIRPATH" 2>/dev/null
cp -r ./include/thirdparty/ "$ENV_COCONUTS2D_EXPORT_INCLUDES_DIRPATH" 2>/dev/null
