@startuml Application

start

:Init;

repeat
  : scene = SceneManager()::GetActiveScene();
  : scene.Init();
  : scene.Run();
  : scene.End;
repeat while (m_IsRunning ?) is (yes) not (no)

  : End;

@enduml